(setq frame-resize-pixelwise t)
(setq default-frame-alist '((menu-bar-lines . 0)
                             (tool-bar-lines . 0)
                             (alpha-background . 80)
                             (width . 300)
                             (height . 80)))
